Euphoria/Controllers/ApplicationsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Euphoria.Context;
using Euphoria.Models;

/// <summary>
/// Summary description for SoulWorkerController
/// </summary>
public class ApplicationsController : Controller
{
    private ApplicationUserManager _userManager;

    public ApplicationUserManager UserManager
    {
        get
        {
            return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
        }
        private set
        {
            _userManager = value;
        }
    }

    public ViewResult View(int id)
    {

        using (var db = new Connection())
        {
            ApplicationsViewModel News = db.Applications.Where(a => a.ApplicationID == id).Select(a => new ApplicationsViewModel
            {
                ApplicationID = a.ApplicationID,
                ApplicationDate = a.ApplicationDate,
                CharacterName = a.CharacterName,
                Game = a.Game,
                Answers = a.Answers,
                Status = a.Status
            }).Single();
            ViewData["UserManager"] = UserManager;
            return View(News);
        }
    }

    [ChildActionOnly]
    public ActionResult Get()
    {
        using (var db = new Connection())
        {
            IList<ApplicationsViewModel> Applications = db.Applications.Select(a => new ApplicationsViewModel
            {
                ApplicationID = a.ApplicationID,
                ApplicationDate = a.ApplicationDate,
                CharacterName = a.CharacterName,
                Game = a.Game,
                Answers = a.Answers,
                Status = a.Status
            }).Where(s => s.Status == "Pending").OrderByDescending(d => d.ApplicationDate).Take(10).ToList();
            return PartialView(Applications);
        }
    }

    [ChildActionOnly]
    public ActionResult GetAll()
    {
        using (var db = new Connection())
        {
            IList<ApplicationsViewModel> Applications = db.Applications.Select(a => new ApplicationsViewModel
            {
                ApplicationID = a.ApplicationID,
                ApplicationDate = a.ApplicationDate,
                CharacterName = a.CharacterName,
                Game = a.Game,
                Answers = a.Answers,
                Status = a.Status
            }).OrderByDescending(d => d.ApplicationDate).Take(10).ToList();
            return PartialView(Applications);
        }
    }

    [AllowAnonymous]
    public ActionResult Confirm()
    {
        return View();
    }
}

Euphoria/Controllers/NewsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Euphoria.Context;
using Euphoria.Models;
using Euphoria;

/// <summary>
/// Summary description for SoulWorkerController
/// </summary>
public class NewsController : Controller
{
    private ApplicationUserManager _userManager;

    public ApplicationUserManager UserManager
    {
        get
        {
            return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
        }
        private set
        {
            _userManager = value;
        }
    }

    [AllowAnonymous]
    public ActionResult Add()
    {
        if (!Request.IsAuthenticated)
        {
            return RedirectToAction("Login", "Account");
        }
        else if (Request.IsAuthenticated && !UserManager.IsInRole(User.Identity.GetUserId(), "Admin"))
        {
            return RedirectToAction("Home", "Home");
        }
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Add(NewsViewModel model)
    {
        if (ModelState.IsValid)
        {
            string urlpath = Server.MapPath(@"~\Images\Uploads\") + model.FeaturedImage.FileName;

            model.FeaturedImage.SaveAs(urlpath);

            //DB connection
            var connection = ConfigurationManager.ConnectionStrings["EuphoriaDB"];

            //Store article in database
            using (SqlConnection conn = new SqlConnection(connection.ConnectionString))
            {
                using (SqlCommand command = new SqlCommand() { CommandType = System.Data.CommandType.StoredProcedure, CommandText = "AddNews", Connection = conn })
                {
                    conn.Open();
                    command.Parameters.AddWithValue("@Content", model.Content);
                    command.Parameters.AddWithValue("@Author", User.Identity.GetUserName());
                    command.Parameters.AddWithValue("@Category", model.Category);
                    command.Parameters.AddWithValue("@Title", model.Title);
                    command.Parameters.AddWithValue("@Image", "Images/Uploads/" + model.FeaturedImage.FileName);
                    command.ExecuteNonQuery();
                }
            }
        }
        return View();
    }

    public ViewResult View(int id)
    {

        using (var db = new Connection())
        {
            NewsViewModel News = db.News.Where(n => n.ArticleID == id).Select(n => new NewsViewModel
            {
                ArticleID = n.ArticleID,
                Author = n.Author,
                Content = n.Content,
                Published = n.Published,
                Title = n.Title,
                Category = n.Category,
                FeaturedImagePath = n.Image
            }).Single();
            ViewData["UserManager"] = UserManager;
            return View(News);
        }
    }

    [ChildActionOnly]
    public ActionResult Get()
    {
        using (var db = new Connection())
        {
            IList<NewsViewModel> NewsList = db.News.Select(n => new NewsViewModel
            {
                ArticleID = n.ArticleID,
                Author = n.Author,
                Content = n.Content,
                Published = n.Published,
                Title = n.Title,
                Category = n.Category,
                FeaturedImagePath = n.Image
            }).OrderByDescending(d => d.Published).ToList();

            return PartialView(NewsList);
        }
    }

    [ChildActionOnly]
    public ActionResult GetComments(int id)
    {
        //DB connection
        using (var connection = new Procedures())
        {
             IEnumerable<CommentsViewModel> CommentsList = connection.GetNewsComments(id).Select(c => new CommentsViewModel
             {
                 ArticleID = c.ArticleID,
                 Author = c.UserName,
                 AuthorPicture = c.ProfilePicture,
                 CommentDate = c.CommentDate,
                 CommentID = (int) c.CommentID,
                 CommentMsg = c.CommentMsg,
                 ParentID = (int) c.ParentID
             }).ToList();
             return PartialView(CommentsList);
        }
    }

    /*[ChildActionOnly]
    public ActionResult GetComments(int id)
    {
        using (var db = new Connection())
        {
            IList<CommentsViewModel> CommentList = db.Comment.Select(c => new CommentsViewModel
            {
                ArticleID = c.ArticleID,
            }).OrderByDescending(d => d.CommentDate).ToList();
            return PartialView(CommentList);
        }
    }*/

    [HttpPost]
    [System.Web.Mvc.Authorize]
    [ValidateAntiForgeryToken]
    public ActionResult AddComment(CommentsViewModel model)
    {
        if (ModelState.IsValid)
        {
            using (var db = new Connection())
            {
                var comments = db.Set<Comment>();
                Comment com = new Comment
                {
                    ArticleID = model.ArticleID,
                    ParentID = model.ParentID,
                    CommentMsg = model.CommentMsg,
                    UserID = model.UserID
                };
                comments.Add(com);
                db.SaveChanges();
                var context = GlobalHost.ConnectionManager.GetHubContext<Feed>();
                Euphoria.Context.User user = db.Users.Where(u => u.UserId == model.UserID).FirstOrDefault();
                string message = "";
                if (model.ParentID > 0)
                {
                    message = "<a href='/Profile/" + user.UserName + "'>" + user.UserName + "</a> replied to a comment in <a href='/News/View/" + model.ArticleID + "#Comment" + com.CommentID + "'>" + db.News.Where(n => n.ArticleID == model.ArticleID).FirstOrDefault().Title + "</a>";
                }
                else
                {
                    message = "<a href='/Profile/" + user.UserName + "'>" + user.UserName + "</a> commented on <a href='/News/View/" + model.ArticleID + "#Comment" + com.CommentID + "'>" + db.News.Where(n => n.ArticleID == model.ArticleID).FirstOrDefault().Title + "</a>";
                }
                context.Clients.All.addNewMessageToPage(user.ProfilePicture, message);
                var feed = db.Set<Activity>();
                feed.Add(new Activity { ImageSrc = user.ProfilePicture, Message = message });
                db.SaveChanges();
                return RedirectToAction("View", "News", new
                {
                    id = model.ArticleID
                });
            }
        }
        else
        {
            return RedirectToAction("View", "News", new
            {
                id = model.ArticleID
            });
        }
    }


    [AllowAnonymous]
    public ActionResult Confirm()
    {
        return View();
    }
}

Euphoria/Views/News/Add.cshtml
@model Euphoria.Models.NewsViewModel
@using Euphoria.Models

@{
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
    ViewBag.Title = "New Article";
    ApplicationUserManager UserManager = (ApplicationUserManager)ViewData["UserManager"];
}

@section page {
    <div class="PageContainer">
    @using (Html.BeginForm("Add", "News", FormMethod.Post, new { role = "form", encType = "multipart/form-data" }))
    {
        @AntiForgery.GetHtml()
        <div class="StandardPageBox MainContent">
            <div class="blur"></div>
            <div class="BoxHeader"><div class="invert"></div><div class="HeaderText">Add News</div></div>
            <div class="Content WithHeader">
                <h1 class="Header">Content</h1>
                @Html.TextAreaFor(m => m.Content, new { id = "Editor" })
            </div>
        </div>
        <div class="StandardPageBox SideMenu">
            <div class="blur"></div>
            <div class="Content SideFormBox">
                <div class="question">
                    <h1 class="Header">Article Title</h1>
                    @Html.TextBoxFor(m => m.Title)
                </div>
                <div class="question">
                    <h1 class="Header">Featured Image</h1>
                    @Html.ValidationMessageFor(m => m.FeaturedImage)
                    <div class="featuredImage" id="featuredPreview" style="background-image: url('/Images/blank.jpg')"></div>
                    @Html.TextBoxFor(m => m.FeaturedImage, new { type = "file", id = "featuredInput", @class = "fileInput", name="FeaturedImage" })
                    <label for="featuredInput" class="fileButton">
                        <i class="fas fa-upload"></i> <span class="fileButtonText">Upload Image</span>
                    </label>
                </div>
                <div class="question">
                    <h1 class="Header">Category</h1>
                    @Html.DropDownListFor(m => m.Category, new SelectList(new List<string> {"Announcements", "Events", "Site Updates"}), "Select a Category", new { @class = "form-control" })
                </div>
                <div class="question submitButton">
                    <input type="submit" value="Create Article" class="SubmitButton" />
                </div>
            </div>
        </div>
    }
    </div>
}

@section scripts {
    <script src="~/Scripts/textboxio.js"></script>
    <script>
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#featuredPreview').css("background-image", "url('" + e.target.result + "')");
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $(document).ready(function () {
            var config = {
                css: {
                    documentStyles: 'body { color: white; }',
                    styles: [
                        { rule: 'p' },
                        { rule: 'h1.Header', text: 'Header' }
                    ],
                    showDocumentStyles: true
                }
            };
            var textareaEditor = textboxio.replace('#Editor', config);
            $("#featuredInput").change(function () {
                readURL(this);
            });
            $('.fileInput').each(function () {
                var $input = $(this),
                    $label = $input.next('label'),
                    labelVal = $label.html();

                $input.on('change', function (e) {
                    var fileName = '';

                    if (this.files && this.files.length > 1)
                        fileName = (this.getAttribute('data-multiple-caption') || '').replace('{count}', this.files.length);
                    else if (e.target.value)
                        fileName = e.target.value.split('\\').pop();

                    if (fileName)
                        $label.find('span').html(fileName);
                    else
                        $label.html(labelVal);
                });

                // Firefox bug fix
                $input
                    .on('focus', function () { $input.addClass('has-focus'); })
                    .on('blur', function () { $input.removeClass('has-focus'); });
            });
        });
    </script>
}

Euphoria/Views/News/AddComment.cshtml
@model Euphoria.Models.CommentsViewModel
@using Euphoria.Models

<div id="CommentForm">
    @using (Html.BeginForm("AddComment", "News", FormMethod.Post, new { role = "form", encType = "multipart/form-data", id="ReplyForm" }))
    {
        @AntiForgery.GetHtml()
        @Html.HiddenFor(m => m.ArticleID)
        @Html.HiddenFor(m => m.ParentID, new { id = "ParentID" })
        @Html.HiddenFor(m => m.UserID)
        @Html.TextAreaFor(m => m.CommentMsg, new { id = "Comment", maxlength = "5000", minlength = "10"})
        <input type="submit" value="Comment" class="CommentButton" />
        <p class="Subtitle" id="ReplyCancelCaption">You're replying to a comment. Click <span id="ReplyCancel">here</span> to cancel.</p>
    }
</div>

Euphoria/Views/News/Get.cshtml
@using Microsoft.AspNet.Identity;
@using Euphoria.Models;
@model IEnumerable<Euphoria.Models.NewsViewModel>
@foreach (var item in Model)
{
    <a href="~/News/View/@item.ArticleID">
        <div class="NewsListImage" style="background-image: url('@(String.IsNullOrEmpty(item.FeaturedImagePath) ? "~/Images/blank.jpg" : item.FeaturedImagePath)')">
            <div class="NewsDescription">
                <h1 class="NewsHeader">@Html.DisplayFor(modelItem => item.Title)</h1>
                <span class="Subtitle">
                    <span class="Category-@item.Category">@item.Category</span> | <time class="timeago" datetime="@item.Published.ToLocalTime()">@item.Published.ToLocalTime().ToString("MMMM dd, yyyy")
                    </time>
                </span>
            </div>
        </div>
    </a>
}

Euphoria/Views/News/GetComments.cshtml
@using Microsoft.AspNet.Identity;
@using Euphoria.Models;
@using System.Xml.Linq;
@model IEnumerable<Euphoria.Models.CommentsViewModel>

@if (Model.Any())
{
    List<CommentsViewModel> parentComments = Model.Where(comment => comment.ParentID == 0).ToList();
    foreach (var comment in parentComments)
    {
        bool hasChildren = Model.Where(child => child.ParentID == comment.CommentID).Any();
        <div class="Comment" id="@(@comment.ParentID == 0 ? "Comment" + comment.CommentID : "ReplyToComment" + comment.ParentID)">
            <div class="AvatarSection @(@comment.ParentID == 0 ? "RegularCommentAvatarSection" : "ReplyAvatarSection")">
                <div class="AvatarSmall" style="background-image: url('/@(String.IsNullOrEmpty(comment.AuthorPicture) ? "Images/blank.jpg" : comment.AuthorPicture)')"></div><div class="RepliesToggle">
                    <a href="javascript:void(0)" id="ReplyToggle@(comment.CommentID)">
                        @if (hasChildren)
                        {
                            <i class="fas fa-chevron-circle-down"></i>
                        }
                    </a>
                </div>
            </div>
            <div id="CommentContentContainer@(comment.CommentID)" class="@(@comment.ParentID == 0 ? "RegularCommentContent" : "ReplyContent") CommentContent">
                <div class="CommentContentStyle">
                    <div class="CommentHeader">
                        <span class="CommentAuthor">
                            <a href="">@comment.Author</a>
                        </span>
                        <span class="CommentDate">
                            <time class="timeago" datetime="@((comment.CommentDate ?? DateTime.Now).ToLocalTime())">@((comment.CommentDate ?? DateTime.Now).ToLocalTime().ToString("MMMM dd, yyyy"))</time>
                        </span>
                    </div>
                    <div>@Html.Raw(comment.CommentMsg)</div>
                    <div class="CommentFooter">
                        <span class="CommentFooterMetaData">
                            @if (@comment.ParentID > 0)
                            {
                                <i class="fas fa-at"></i>@Model.Where(c => c.CommentID == comment.ParentID).FirstOrDefault().Author
                            }
                        </span>
                        <span class="ReplyButton" id="ReplyButton@(comment.CommentID)"><i class="fas fa-reply ReplyIcon"></i> Reply</span>
                    </div>
                </div>
            </div>
        </div>
        if (hasChildren)
        {
            @FindChildren(comment.CommentID);
        }
    }
}

@helper FindChildren(int parentID)
{
    List<CommentsViewModel> children = Model.Where(comment => comment.ParentID == parentID).ToList();
        <div id="Thread@(parentID)">
            @foreach (var comment in children)
            {
                bool hasChildren = Model.Where(child => child.ParentID == comment.CommentID).Any();
                <div class="Comment" id="Comment@(comment.CommentID)">
                    <div class="AvatarSection @(@comment.ParentID == 0 ? "RegularCommentAvatarSection" : "ReplyAvatarSection")">
                        <div class="AvatarSmall" style="background-image: url('/@(String.IsNullOrEmpty(comment.AuthorPicture) ? "Images/blank.jpg" : comment.AuthorPicture)')"></div><div class="RepliesToggle">
                            <a href="javascript:void(0)" id="ReplyToggle@(comment.CommentID)">
                                @if (hasChildren)
                                {
                                    <i class="fas fa-chevron-circle-down"></i>
                                }
                            </a>
                        </div>
                    </div>
                    <div id="CommentContentContainer@(comment.CommentID)" class="@(@comment.ParentID == 0 ? "RegularCommentContent" : "ReplyContent") CommentContent">
                        <div class="CommentContentStyle">
                            <div class="CommentHeader">
                                <span class="CommentAuthor">
                                    <a href="">@comment.Author</a>
                                </span>
                                <span class="CommentDate">
                                    <time class="timeago" datetime="@((comment.CommentDate ?? DateTime.Now).ToLocalTime())">@((comment.CommentDate ?? DateTime.Now).ToLocalTime().ToString("MMMM dd, yyyy"))</time>
                                </span>
                            </div>
                            <div>@Html.Raw(comment.CommentMsg)</div>
                            <div class="CommentFooter">
                                <span class="CommentFooterMetaData">
                                    @if (@comment.ParentID > 0)
                                    {
                                        <i class="fas fa-at"></i>@Model.Where(c => c.CommentID == comment.ParentID).FirstOrDefault().Author
                                    }
                                </span>
                                <span class="ReplyButton" id="ReplyButton@(comment.CommentID)"><i class="fas fa-reply ReplyIcon"></i> Reply</span>
                            </div>
                        </div>
                    </div>
                </div>
                if (hasChildren)
                {
                    @FindChildren(comment.CommentID);
                }
            }
        </div>
}

Euphoria/Views/News/View.cshtml
@model Euphoria.Models.NewsViewModel

@using Microsoft.AspNet.Identity;
@using Euphoria.Models;

@{
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
    ViewBag.Title = Model.Title;
    ApplicationUserManager UserManager = (ApplicationUserManager)ViewData["UserManager"];
}

@section page {
    <div class="PageContainer">
        <div class="StandardPageBox MainContent">
            <div class="blur"></div>
            <div class="BoxHeader"><div class="invert"></div><div class="HeaderText">@Model.Title</div></div>
            <div class="Content WithHeader" id="MainContentBox">
                @Html.Raw(Model.Content)
                <h1 class="CommentsHeader">Comments</h1>
                @{Html.RenderAction("GetComments", "News", Model.ArticleID);}
                @Html.Partial("AddComment", new CommentsViewModel { UserID = User.Identity.GetUserId(), ArticleID = Model.ArticleID })
            </div>
        </div>

        @Html.Partial("_SideMenu")

        @if (UserManager.IsInRole(User.Identity.GetUserId(), "Admin"))
        {
            @Html.Action("Get", "Applications")
        }
    </div>
}

@section scripts {
    <script src="~/Scripts/jquery.timeago.js" type="text/javascript"></script>
    <script src="~/Scripts/locales/jquery.timeago.en.js" type="text/javascript"></script>
    <script src="~/Scripts/textboxio.js"></script>
    <script>
        $(document).ready(function () {
            var urlHash = window.location.href.split("#")[1];
            if (urlHash && $('#' + urlHash).length) {
                $('#' + urlHash + ' .CommentContentStyle:first-child').css("background-color", "rgb(62, 170, 234, 0.2)");
                $('html,body').animate({
                    scrollTop: $('#' + urlHash).offset().top - 150
                }, 4000);
            }
            var config = {
                css: {
                    documentStyles: 'body { color: white; }',
                    styles: [
                        { rule: 'p' },
                        { rule: 'h1.Header', text: 'Header' }
                    ],
                    showDocumentStyles: false
                },
                codeview: {
                    enabled: false,
                    showButton: false
                }
            };
            var textareaEditor = textboxio.replace('#Comment', config);
            $.timeago.settings.cutoff = 1000 * 60 * 60 * 24;
            $.timeago.settings.locale = 'en';
            $("time.timeago").timeago();
            tippy('.Control', {
                arrow: true,
                placement: 'top'
            });
            $("[id^=ReplyToggle]").each(function (index) {
                var commentID = this.id.slice(11);
                var fullID = this.id;
                $(this).click(function () {
                    if ($("#" + fullID).html() == "<i class=\"fas fa-chevron-circle-right\"></i>") {
                        $("#Thread" + commentID).slideToggle("slow", function () {
                            // Animation complete.
                        });
                        $("#" + fullID).html("<i class=\"fas fa-chevron-circle-down\"></i>");
                    }
                    else {
                        $("#Thread" + commentID).slideToggle("slow", function () {
                            // Animation complete.
                        });
                        $("#" + fullID).html("<i class=\"fas fa-chevron-circle-right\"></i>");
                    }
                });
            });
            $("[id^=ReplyButton]").each(function (index) {
                var replyCommentID = this.id.slice(11);
                $(this).click(function () {
                    $("#ParentID").val(replyCommentID);
                    textareaEditor.restore();
                    $(".CommentButton").val("Reply");
                    $("#ReplyForm").appendTo("#CommentContentContainer" + replyCommentID);
                    $("#ReplyCancelCaption").show();
                    textareaEditor = textboxio.replace('#Comment', config);
                });
            });
            $("#ReplyCancel").click(function () {
                $("#ParentID").val(0);
                textareaEditor.restore();
                $(".CommentButton").val("Comment");
                $("#ReplyForm").appendTo("#CommentForm");
                $("#ReplyCancelCaption").hide();
                textareaEditor = textboxio.replace('#Comment', config);
            });
        });
    </script>
}